clone:
  path: github.com/udistrital/titan_api_crud

build:

  go:
    image: golang:1.8
    commands:
     - go get
     - go build -o main
    when:
      branch: develop
      event: push

publish:

  docker:
    repo: oas0/titan_api_crud
    tag:
      - latest
      - desarrollo
      - $$COMMIT
    username: oas0
    password: $$DOCKER_PUBLISH_PASSWORD
    email: computoud@googlegroups.com
    when:
      branch: develop
      event: push
