clone:
  path: github.com/udistrital/titan_api_crud

build:

  go:
    image: golang:1.8
    commands:
     - go get
     - go build -o main
    when:
      branch: develop
      event: push

  docker:
    image: plugins/docker
    repo: titan_api_crud
    tags: desarrollo
    when:
      branch: develop
      event: push
